version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ls
      - pwd
        #      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 698045063618.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - aws s3 sync s3://demo-env-file/env.txt
      - ls -l
        #- docker build -t elastic-beanstalk .
        #- docker tag elastic-beanstalk:latest 698045063618.dkr.ecr.us-east-1.amazonaws.com/elastic-beanstalk:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - ls
        #- docker push 698045063618.dkr.ecr.us-east-1.amazonaws.com/elastic-beanstalk:latest
artifacts:    
  files:
    - '**/*'
